bbqsrc/cargo-ndk

README.md
src/main.rs

- uses PathBuf instead of String for path creation
- adds windows ARCH
- adds windows ".cmd" extension for linker/compiler

Windows support

---

src/cargo.rs
src/cli.rs

Closes: https://github.com/bbqsrc/cargo-ndk/issues/11
respect --manifest-path

Respect manifest-path to allow builds outside rust project

---

src/meta.rs

add match on the rust style triples for the targets
This should fix #15

Fix for backwards compatibility with 1.0.0

---

Cargo.toml
src/cargo.rs
src/cli.rs
src/main.rs

Currently `cargo-ndk` only tries to find the latest NDK version when either `ANDROID_SDK_HOME` is defined or none of the typical env vars are present. For `ANDROID_NDK_HOME` and `NDK_HOME` however, no resultion is currently done.
This adds the missing resolution step but allows a fallback in case the env var doesn't point to the `.../ndk` folder but already a specific version like `.../ndk/X.Y.Z`.
I updated all deps to the latest version as well. That was mostly done to avoid dependency duplicates as semver was already pulled in as transitive dependency.

Try find the highest NDK version from NDK env var

---

src/cli.rs

This is the only variable that is left.
NDK uses 16 by default so it would be better to expose this variable too

Expose API level to user

---

src/cargo.rs
src/cli.rs

This is a minor modification on #53 to get it merged. The behaviour is now no longer always active, but can be enabled with the `--bindgen` flag. I was able to check, with our own build, that both absent and present `--bindgen` flag works as expected for us.

Add ability to pass sysroot setting when building w/ bindgen

---

src/cargo.rs
src/cli.rs

libgcc was removed from NDK v23 which breaks Rust builds against pre-built standard libraries that were linked against libgcc instead of libunwind.
As a workaround this ensures that there is a libgcc.a in the library search paths which is a linker script that will redirect to link with libunwind instead.
The libgcc.a linker script is created under:
`target/cargo-ndk/libgcc_workaround/libgcc.a`
Fixes: #22
_For reference the underlying issue has been fixed upstream but it still depends on building the std library from source (via [`-Zbuild-std`](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std)) instead of using the pre-built libraries distributed via rustup. This currently means using a nightly toolchain. See: https://github.com/rust-lang/rust/pull/85806_

Provide libgcc linker script workaround for NDK >= 23

---

src/cli.rs

There's not really any 'correct' variables to use for detecting an
Android NDK or SDK but there are some more common variables that
cargo-ndk can check to maximize the chance of finding an NDK based
on a user's existing environment.
This fixes a minor paper-cut issue that just reduces the need
to store the NDK/SDK paths in multiple environment variables to
appease different tools that check different variables.
They are approximately (subjectively) checked in order of officialness.

Consider all widely-used NDK/SDK env vars

---

src/cargo.rs

I think this is supposed to be defined by Clang, but it isn't.

Define __ANDROID_API_ so only the correct APIs get used

---

src/cli.rs

This PR removes the `.unwrap()` call on:
```rust
let so_files = std::fs::read_dir(&dir)
.ok()
.unwrap()
.flat_map(Result::ok)
.map(|x| x.path())
.filter(|x| x.extension() == Some(OsStr::new("so")))
.collect::<Vec<_>>();
```
And instead logs the error to the console.
I just spent an hour trying to build a library with `cargo ndk -t x86_64 -o app/src/main/jniLibs/  build -r` and it always failed until I noticed that cargo-ndk tries to copy from the debug and not the release folder.
I hope this will save time for someone else in the future :smiley:

handle error if moving of .so file fails

---

src/cargo.rs

This PR fixes sysroot paths #84 
My little research led me to the fact that for some reason `\\` disappears from the paths

Fix windows slash in sysroot path

---

Cargo.lock
Cargo.toml
src/cargo.rs
src/main.rs

Fixes #92.
@TomieAi can you test this and let me know if it fixes your issue?
```
cargo install --git https://github.com/bbqsrc/cargo-ndk --branch feature/windows-r25-workaround
```

Create an abomination

---

Cargo.lock
Cargo.toml
src/cargo.rs
src/main.rs

_Okey, yet another iteration on figuring out how to handle this. This is my last idea for now ;-p_ 
This is an alternative workaround for #92 that's similar to the [solution used in ndk-build](https://github.com/rust-mobile/ndk/pull/306) except that the `--target=<triple><api-level>` argument for Clang is injected by using cargo-ndk as a linker wrapper instead of trying to modify CARGO_ENCODED_RUSTFLAGS.
It turned out to be practically impossible to be able to reliably set CARGO_ENCODED_RUSTFLAGS without risking trampling over rustflags that might be configured via Cargo (for example `target.<cfg>.rustflags` are especially difficult to read outside of cargo itself)
This approach avoids hitting the command line length limitations of the current workaround and avoids needing temporary hard …

Use cargo-ndk as a _LINKER wrapper to pass --target to Clang

---

src/cargo.rs

Although the changes in d6cdbf4feef48ebea5eee8958e9c98431c3c5f32 set up a `cflags_key` + `cxxflags_key` and values that would pass `--target=<triple><api-level>` to the compiler; these didn't actually get passed via `.env()` when building the command to run cargo.
This means that the `cc` crate doesn't use the right api-level when compiling C/C++ code since it doesn't find the `CFLAGS_` and `CXXFLAGS_` that we intended to export.
This recently caused an issue while testing the game-activity backend for android-activity on older versions of android because when targeting levels < 29 then any use of the `android_get_device_api_level` API needs to be inlined and that isn't currently happening - which leads to a runtime failure to lookup the symbol.
Ref: …

export CFLAGS_ and CXXFLAGS_ when run cargo

---

src/cli.rs
src/meta.rs

As in https://github.com/bbqsrc/cargo-ndk/issues/89, we build multiple ffi libraries in the same cargo workspace. `cargo-ndk` ends up copying all libraries in the target directory instead of only the ones built for that invocation. Gradle then will complain with something like `2 files found with path 'lib/arm64-v8a/libffi.so' from inputs` in the merge JNI libraries step.
This change parses the library name from Cargo.toml and copies only the library (per target) to the output directory. I'm not sure if this will end up missing some libraries in copy. As far as I can tell, every rust crate can have 0 or 1 libraries, and `package.name` is required in `Cargo.toml` so we always have a name.
The library name is derived from `lib.name` if set, or from `package.name` if not, per …

copy only the libraries that were built

---

CHANGELOG.md
src/cli.rs

- Fix: canonicalize output directory path for `CARGO_NDK_OUTPUT_PATH`, fixes build scripts not at workspace root  
closes #139
- Enhancement: output directory creation error now prints error message instead of panicking, 
closes #138

Enhance output path handling

---

Cargo.lock
Cargo.toml
src/cargo.rs
src/cli.rs
src/meta.rs

Change the way output binaries are selected, as the current implementation relies on CLI args that might change easily and don't cover all possible scenarios.
Instead, the already used `cargo_metadata` can parse the diagnostic output from Cargo which reports any artifacts produced, giving a reliable list of any produced file of interest.

Fix selection of output libs to copy

---

CHANGELOG.md
src/cli.rs

Silly bug introduced by me in #140. Canonicalize needs the path to exist.
For the other pull request I only tested in a project that already creates the path and a case where a file already exists in the path (the panic issue). I have now tested with a relative path that does not exist too.

Fix: create output dir before canonicalize

---

src/cargo.rs

In relation to the issue I created here https://github.com/bbqsrc/cargo-ndk/issues/156, I started looking deeper into Rust Bindgen issues and found some things that indicated `bindgen` was using the wrong clang with `clang-sys`. The environment provided allows `clang-sys` to use Android NDK clang and setup properly. The extension is required on Windows.
It seems to be working properly, at least finding the headers. 
Relation:
https://github.com/rust-lang/rust-bindgen/issues/2962
https://github.com/KyleMayes/clang-sys?tab=readme-ov-file#environment-variables
Fixing this resolves https://github.com/bbqsrc/cargo-ndk/issues/156 in my use case at least.

Fix wrong clang used on Windows

---

src/cargo.rs

Referencing the original issue here, https://github.com/rust-lang/compiler-builtins/issues/468, it seems some builtins for Android aren't included properly. This adds flags that links the proper builtins statically. 
The default clang version constant is undesirable but I'm not sure how else to do it.

Add support for runtime builtins
